### PR TITLE
Fix for hover on icon buttons

### PR DESCRIPTION
**Pull request by vulcanr**

### CODE REVIEW

**Comment by vulcanr** [comment]
Switching to regular display none and display block.

**Comment by dbazuin** [comment]
Is this the same issue as #225?
In that case it is solved.

**Comment by vulcanr** [comment]
Yes, this is the fix for #225 i don't see it is solved.

**Comment by dbazuin** [comment]
Your commit will solves this issue.

**Review by dbazuin — APPROVED** [review]

**Pull request merged**
